name: CI Audit Security

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r backend/requirements.txt

      - name: Run security audit
        run: |
          python - <<EOF
import os, json
from backend.parsers.python_parser import parse_python_code
from backend.detectors.sql_injection import SQLInjectionDetector
from backend.reporting.vulnerability_reporter import VulnerabilityReporter

vulns = []
for root, _, files in os.walk("backend"):
    for f in files:
        if f.endswith(".py"):
            path = os.path.join(root, f)
            code = open(path, encoding="utf-8").read()
            detector = SQLInjectionDetector()
            vulns.extend(detector.analyze_sql_injection(code))

report = VulnerabilityReporter().generate_report(vulns, {"repository": os.getenv("GITHUB_REPOSITORY")})
with open("audit_report.json", "w", encoding="utf-8") as out:
    json.dump(report, out, indent=2)
EOF

      - name: Upload audit report
        uses: actions/upload-artifact@v3
        with:
          name: security-audit-report
          path: audit_report.json
